---
linters:
  enable-all: true
  disable:
    - 'depguard'
    - 'tagliatelle'

    # Temporary
    - 'cyclop'
    - 'dupl'
    - 'err113'
    - 'exhaustruct'
    - 'forbidigo'
    - 'funlen'
    - 'gochecknoglobals'
    - 'gocognit'
    - 'goconst'
    - 'gocritic'
    - 'gocyclo'
    - 'godox'
    - 'gosec'
    - 'lll'
    - 'maintidx'
    - 'mnd'
    - 'nestif'
    - 'nlreturn'
    - 'paralleltest'
    - 'perfsprint'
    - 'revive'
    - 'stylecheck'
    - 'varnamelen'
    - 'wrapcheck'
    - 'wsl'

    # Deprecated
    - 'exportloopref'
